name: '🚧 Development Build'

on:
  push:
    branches:
      - '**' # This prevents dev builds on tag pushes
  workflow_dispatch:

jobs:
  dev-build:
    name: '🚧 Development Build'
    uses: acidicoala/SmokeAPI/.github/workflows/matrix-build.yml@master
